name: MobMetrics
channels:
  - conda-forge
  - defaults
dependencies:
  - django=5.0.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.10.1=py310hd28fd6d_0
  - numpy=2.0.1=py310heeff2f4_1
  - numpy-base=2.0.1=py310h8a23956_1
  - openssl=3.0.16=h5eee18b_0
  - pandas=2.2.3=py310h6a678d5_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.15.2=py310h210a465_1
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sqlparse=0.5.2=py310h06a4308_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.67.1=py310h2f386ee_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
